--- #YAML:1.0
name:                File-LogReader
version:             0.03
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Digest::SHA1:                  0
    Test::More:                    0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Luke Closs <file-logreader@5thplane.com>
